### ISSUE TITLE
Default to "Unknown" if Primary Language undetected

### ISSUE THREAD

**Issue by davesgonechina** [glasnt/glasnt#7]
When a public repo has no primary language detected by Git Linguist, `build README.md` fails with the following:

```
Run python build.py
Traceback (most recent call last):
  File "build.py", line 236, in <module>
    {n["primaryLanguage"]["name"]} ✭ {n["stargazers"]["totalCount"]} ↡ {forks}"""
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.
```

In these cases, a user can add/modify a `.gitattributes` for every repo where Linguist fails to assign a primary language, but `glasnt` could also default on a `NoneType` to a string like `Unknown`.

**Comment by glasnt** [comment]
This has been fixed in c7518af01ab4e30422a89dff332b3060dcadb879
